services:
  jenkins:
      build: .
      container_name: jenkins
      restart: always
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - ./jenkins_home:/var/jenkins_home

        - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d:ro
      environment:
        JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic

volumes:
  jenkins_home:
